<?php

namespace AppBundle\Repository;

/**
 * AccountsStatementFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsStatementFileRepository extends \Doctrine\ORM\EntityRepository
{
    /*
   public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Accounts e ORDER BY e.id ASC'
            )
            ->getResult();
    } 
     * *
     */      
}
