<?php

namespace AppBundle\Repository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends \Doctrine\ORM\EntityRepository
{
   public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Account e ORDER BY e.id ASC'
            )
            ->getResult();
    }

	public function findByAccountReference($accountReference)
    {
        $query= $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Account e WHERE e.accountReference = :accountReference')
            ->setParameter("accountReference",$accountReference)
                ;

            return $query->getSingleResult();
    }       

}
