<?php

namespace AppBundle\Repository;

/**
 * EnvironmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironmentRepository extends \Doctrine\ORM\EntityRepository
{
   public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Environment e ORDER BY e.name ASC'
            )
            ->getResult();
    }       
    public function findByEnvId($envid)
    {
        $query= $this->getEntityManager()
            ->createQuery(
                'SELECT e, ed FROM AppBundle:Environment e 
                    JOIN e.envDetails ed
                    WHERE e.id = :envid'
            )->setParameter('envid', $envid);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }    }
}
