<?php

namespace AppBundle\Repository;

/**
 * TransferAccountsStatementFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferAccountsStatementFileRepository extends \Doctrine\ORM\EntityRepository
{
    /*
   public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:Accounts e ORDER BY e.id ASC'
            )
            ->getResult();
    }      
     * 
     */ 
   public function findByFileId($fileId)
    {
       // TODO WHERE CLAUSE
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:TransferAccountsStatementFile e where e.accountsStatementFileId='.$fileId)        
            ->getResult();
    }      

   public function findFileIdByUserId($userId)
    {
       // TODO WHERE CLAUSE
        return $this->getEntityManager()
            ->createQuery(
                'SELECT distinct(e.accountsStatementFileId) FROM AppBundle:TransferAccountsStatementFile e where e.user='.$userId)        
            ->getResult();
    }
}
